[install]
is_configured = false
build = 1

[ui]
is_visible = true
label = Flowtriq DDoS Detection

[launcher]
author = Flowtriq
description = Receive and analyze DDoS detection events from Flowtriq
version = 1.0.0
