[flowtriq_incident]
search = sourcetype="flowtriq:incident"

[flowtriq_attack_start]
search = sourcetype="flowtriq:incident" event_type="attack_start"

[flowtriq_attack_end]
search = sourcetype="flowtriq:incident" event_type="attack_end"

[flowtriq_attack]
search = sourcetype="flowtriq:incident" severity!="low"
