[eventtype=flowtriq_incident]
network = enabled
ids = enabled
attack = enabled

[eventtype=flowtriq_attack]
attack = enabled

[eventtype=flowtriq_attack_start]
attack = enabled

[eventtype=flowtriq_attack_end]
attack = enabled
