# Severity lookup
[flowtriq_severity_lookup]
filename = flowtriq_severity.csv
match_type = EXACT
min_matches = 1
default_match = unknown

# Attack family lookup
[flowtriq_attack_family_lookup]
filename = flowtriq_attack_families.csv
match_type = EXACT
min_matches = 1
default_match = unknown
